# docker-compose.yml (place outside request_manager/)
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - zookeeper

  queue_worker:
    build:
      context: ./queue_worker
    env_file:
      - ./queue_worker/.env-example
    environment:
      WORKER_COUNT: 4
      REQUEST_MANAGER: request_manager:50051
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: jobs
    depends_on:
      - kafka

  request_manager:
    build:
      context: ./request_manager
    env_file:
      - ./request_manager/.env-example
    environment:
      PORT_API: 8080
      PORT_GRPC: 50051
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: jobs
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - queue_worker